In [29]:
import two_imgs_matcher
import os
import caffe
import skimage.io as skio
import skimage as sk
import skimage.transform as skt
import skimage.exposure as ske
from skimage.color import rgb2gray
import numpy as np
%matplotlib
import matplotlib.pyplot as plt

Using matplotlib backend: TkAgg


In [30]:
# caffe_model_dir = '../../data/caffe_model/alexnet365/'
# descriptor_path = caffe_model_dir + 'deploy_alexnet_places365.prototxt'
# weights_path = caffe_model_dir + 'alexnet_places365.caffemodel'

caffe_model_dir = '/home/arka_s/Caffe/caffe/models/bvlc_alexnet/'
descriptor_path = caffe_model_dir + 'deploy.prototxt'
weights_path = caffe_model_dir + 'bvlc_alexnet.caffemodel'

ilsvrc_mean_path = '/home/arka_s/Caffe/caffe/python/caffe/imagenet/ilsvrc_2012_mean.npy'
net = caffe.Net(descriptor_path, weights_path, caffe.TEST)
# skimage.io.use_plugin('matplotlib')
skio.use_plugin('matplotlib')
# transformer
transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})
transformer.set_mean('data', np.load(ilsvrc_mean_path).mean(1).mean(1))

transformer.set_transpose('data', (2, 0, 1))
transformer.set_channel_swap('data', (2, 1, 0))
transformer.set_raw_scale('data', 255.0)
net.blobs['data'].reshape(2, 3, 227, 227)
# layer = 'fc8'
# img1_tdir = '../../data/protest_data/only_text/beach_mdf_019/'
# img2_tdir = '../../data/protest_data/only_text/protest_img_019/'
# i = '0.png'
# j = '1.png'
# a1 = two_imgs_matcher.are_the_two_imgs_same(img1_tdir + i,
#                                             img2_tdir + j, transformer, net, layer)


In [49]:
# Checking for scale invariance
import pdb
layer = 'fc8'
img1_fname = '/home/nkovvuri/Rama_Work/dataset/Protest_Images/Pruned_Protest_YFCCImages/protest_img_001.jpg'
img1 = skio.imread(img1_fname)
scales = np.arange(0.05,2.05,0.05)
img_list = []
for sc in scales:
    img_tmp = skt.rescale(img1, sc)
#     pdb.set_trace()
    img_list.append(img_tmp)
img3 = sk.img_as_float(img1)
for ind, im in enumerate(img_list):
    a1 = two_imgs_matcher.are_the_two_imgs_same(img3,im, transformer, net, layer)
    corr = a1[5]['pear_ncc']
    print scales[ind],'  ', corr

    
# img2 = skt.rescale(img1, 0.5)
# skio.imshow_collection([img1, img2])
# skio.imshow(img1)

0.05    0.563068047764
0.1    0.708927242043
0.15    0.674484962948
0.2    0.776984033166
0.25    0.879912024202
0.3    0.921925862867
0.35    0.9556722123
0.4    0.980394447561
0.45    0.981501484884
0.5    0.985761544861
0.55    0.989666551331
0.6    0.9928557046
0.65    0.992844954963
0.7    0.995609142389
0.75    0.994544298064
0.8    0.995711236485
0.85    0.995441865306
0.9    0.996224533531
0.95    0.996714318175
1.0    1.0
1.05    0.997158651906
1.1    0.998047021549
1.15    0.997651866146
1.2    0.998293555693
1.25    0.998305348768
1.3    0.998638515187
1.35    0.99846789258
1.4    0.998869320167
1.45    0.998399690539
1.5    0.998800985989
1.55    0.999157905262
1.6    0.999223793796
1.65    0.999123684678
1.7    0.999291937758
1.75    0.999237961693
1.8    0.999526018857
1.85    0.999619678154
1.9    0.999465631295
1.95    0.999657496645
2.0    0.999176394207


In [39]:
layer = 'fc8'
img1_fname = '/home/nkovvuri/Rama_Work/dataset/Protest_Images/Pruned_Protest_YFCCImages/protest_img_001.jpg'
img1 = skio.imread(img1_fname)
img11 = sk.img_as_float(img1)
# img11 = rgb2gray(img1)
# img11 = sk.img_as_float(img1)
# img21 = ske.rescale_intensity(img11 * 5)
# img21 = ske.rescale_intensity(img11 + 1000000)
# ill_scales = np.arange(0.05,2.05,0.05)
ill_scales = np.arange(1.05,20.05,0.05)

# img21 = np.clip(img11*1.4, 0, 1)
for il_sc in ill_scales:
    img21 = np.clip(img11 * il_sc, 0, 1)
    a1 = two_imgs_matcher.are_the_two_imgs_same(img11,img21, transformer, net, layer)
    corr = a1[5]['pear_ncc']
    print il_sc,'  ', corr

skio.imshow_collection([img11, img21])
# img11[0][0], img21[0][0]

1.05    0.999718882855
1.1    0.998907676253
1.15    0.9975943572
1.2    0.995787345394
1.25    0.994041759732
1.3    0.991727351752
1.35    0.98886113697
1.4    0.986061307198
1.45    0.983845269299
1.5    0.981215276258
1.55    0.978810065122
1.6    0.975762526445
1.65    0.971502683073
1.7    0.967809348564
1.75    0.965020689267
1.8    0.961762341995
1.85    0.959367630312
1.9    0.957003914057
1.95    0.954819292645
2.0    0.952406045184
2.05    0.949645526976
2.1    0.947236518065
2.15    0.943852758097
2.2    0.939705492337
2.25    0.936055644911
2.3    0.933514524868
2.35    0.931582651284
2.4    0.929480479802
2.45    0.927620696232
2.5    0.926178085191
2.55    0.924976521228
2.6    0.923556936856
2.65    0.922318187318
2.7    0.920929656554
2.75    0.918938598742
2.8    0.917105453856
2.85    0.915125747525
2.9    0.91295659711
2.95    0.910256666767
3.0    0.907078518572
3.05    0.90373198258
3.1    0.900381396859
3.15    0.896831106523
3.2    0.892716126158
3.25    0.88805

18.95    0.511898251875
19.0    0.512137556111
19.05    0.512327463565
19.1    0.512525292961
19.15    0.51273504925
19.2    0.512931318589
19.25    0.513125151996
19.3    0.513314779568
19.35    0.513486028894
19.4    0.513634733081
19.45    0.513818514038
19.5    0.513928294866
19.55    0.513998928943
19.6    0.514070182988
19.65    0.51408558751
19.7    0.514084448828
19.75    0.514061630681
19.8    0.514031301495
19.85    0.514000510317
19.9    0.514000667224
19.95    0.514036598462
20.0    0.514035217369


/home/arka_s/internship_files/Viterbi-Internship/my_proj/local/lib/python2.7/site-packages/skimage/io/_plugins/matplotlib_plugin.py:74: UserWarning: Low image data range; displaying image with stretched contrast.
  warn("Low image data range; displaying image with "


In [27]:
ill_scales

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# a1 = two_imgs_matcher.are_the_two_imgs_same(img1,img_list[-1], transformer, net, layer)
img2 = skt.rescale(img1, 1)
print img1.shape, img2.shape
# skio.imshow_collection([img1, img2])
# print img1[0], img2[0]
img3 = sk.img_as_float(img1)
print img1.dtype, img2.dtype, img3.dtype
print img1[0], img2[0], img3[0]

(333, 500, 3) (333, 500, 3)
uint8 float64 float64
[[ 64  77  93]
 [ 64  80  95]
 [ 64  80  95]
 ..., 
 [103 117 128]
 [102 116 127]
 [101 115 126]] [[ 0.25098039  0.30196078  0.36470588]
 [ 0.25098039  0.31372549  0.37254902]
 [ 0.25098039  0.31372549  0.37254902]
 ..., 
 [ 0.40392157  0.45882353  0.50196078]
 [ 0.4         0.45490196  0.49803922]
 [ 0.39607843  0.45098039  0.49411765]] [[ 0.25098039  0.30196078  0.36470588]
 [ 0.25098039  0.31372549  0.37254902]
 [ 0.25098039  0.31372549  0.37254902]
 ..., 
 [ 0.40392157  0.45882353  0.50196078]
 [ 0.4         0.45490196  0.49803922]
 [ 0.39607843  0.45098039  0.49411765]]


In [30]:
# skio.imshow(img1)

In [25]:
scales

array([ 0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,  0.45,
        0.5 ,  0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,  0.9 ,
        0.95,  1.  ])

In [17]:
help(sk.transform.rescale)

Help on function rescale in module skimage.transform._warps:

rescale(image, scale, order=1, mode=None, cval=0, clip=True, preserve_range=False)
    Scale image by a certain factor.
    
    Performs interpolation to upscale or down-scale images. For down-sampling
    N-dimensional images with integer factors by applying a function or the
    arithmetic mean, see `skimage.measure.block_reduce` and
    `skimage.transform.downscale_local_mean`, respectively.
    
    Parameters
    ----------
    image : ndarray
        Input image.
    scale : {float, tuple of floats}
        Scale factors. Separate scale factors can be defined as
        `(row_scale, col_scale)`.
    
    Returns
    -------
    scaled : ndarray
        Scaled version of the input.
    
    Other parameters
    ----------------
    order : int, optional
        The order of the spline interpolation, default is 1. The order has to
        be in the range 0-5. See `skimage.transform.warp` for detail.
    mode : {'constan

  Using cached jupyter-emacskeys-0.2.3.tar.gz


  Running setup.py bdist_wheel for jupyter-emacskeys ... error
  Complete output from command /home/arka_s/internship_files/Viterbi-Internship/my_proj/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4E73vJ/jupyter-emacskeys/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp5JkubYpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/jupyter_emacskeys
  copying jupyter_emacskeys/__init__.py -> build/lib.linux-x86_64-2.7/jupyter_emacskeys
  running egg_info
  writing requirements to jupyter_emacskeys.egg-info/requires.txt
  writing jupyter_emacskeys.egg-info/PKG-INFO
  writing top-level names to jupyter_emacskeys.egg-info/top_level.txt
  writing dependency_links to jupyter_emacskeys.egg-info/dependency_links.txt
  reading manifest f